apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: vm-test-io
  namespace: default
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm-test-io
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: ibm-spectrum-scale-sample
          volumeMode: Filesystem
        source:
          http:
            url: >-
              https://dl.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
    - metadata:
        name: dataiotest
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1000Gi
          storageClassName: ibm-spectrum-scale-sample
          volumeMode: Filesystem
        source:
          blank: {}
  runStrategy: Always 
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: large
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        flavor.template.kubevirt.io/large: 'true'
        kubevirt.io/domain: vm-testvm
        kubevirt.io/size: large
        os.template.kubevirt.io/fedora40: 'true'
        vm.kubevirt.io/name: vm-testvm
        workload.template.kubevirt.io/desktop: 'true'
    spec:
      nodeSelector:
        scale.spectrum.ibm.com/role: storage
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {} 
            source:
              secret:
                secretName: vmkeyroot
      domain:
        cpu:
          cores: 4
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: vm-test-disk
              bootOrder: 1 
            - disk:
                bus: virtio
              name: vm-dataiotest
          inputs:
            - bus: virtio
              name: tablet
              type: tablet
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        resources:
          requests:
            memory: 16Gi
      evictionStrategy: None
      hostname: vm-testvm
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: root
              password: fedora
              chpasswd:
                expire: false
              disable_root: false
          name: cloudinitdisk
          disable_root: false
        - dataVolume:
            name: vm-test-io
          name: vm-test-disk
        - dataVolume:
            name: dataiotest
          name: vm-dataiotest
