metricsEndpoints:
  - indexer:
      type: local
global:
  measurements:
  - name: vmiLatency
  - name: pvcLatency
jobs:
  - name: dv-source
    jobType: create
    jobIterations: 1
    namespacedIterations: true
    namespace: vm-density
    qps: 10000
    burst: 10000
    maxWaitTimeout: 1h
    jobPause: 2m
    objects:
    - objectTemplate: templates/dv-source.yml
      replicas: 1
      inputVars:
        url: https://dl.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
        storage: 6Gi
        storageclass: ibm-spectrum-scale-sample-test
        volumemode: Filesystem

  - name: vm-density
    jobType: create
    jobIterations: 1
    qps: 10000
    burst: 10000
    namespacedIterations: true
    namespace: vm-density
    maxWaitTimeout: 2h
    jobPause: 1m
    objects:
    - objectTemplate: templates/vm-dv.yml
      replicas: {{ .OBJ_REPLICAS }}
      inputVars:
        name: vm-dv-density
        OS: fedora
        cpuCores: 1
        memory: 100Mi
        storage: 6Gi
        storageclass: ibm-spectrum-scale-sample-test
        volumemode: Filesystem
        VMIrunning: true
